name: Frontend S3 Bucket Sync

on:
  push:
    branches:
      - main  # deploy test automatically
      - dev
  workflow_dispatch:  # allows manual triggers for prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # only for main branch

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ARN_PROD }}
          aws-region: ${{ secrets.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Check AWS Credentials
        run: aws sts get-caller-identity

      - name: Deploy frontend and clear CloudFront Cache
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/dev" ]]; then
            aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET_DEV }} --delete
            aws cloudfront create-invalidation --distribution-id E3DZH8GONCYVQK --paths "/*"
          else
            aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET }} --delete
            aws cloudfront create-invalidation --distribution-id E2KBLTVV893N9E --paths "/*"
          fi
